### ISSUE TITLE
Log List - Time Column Resize Bug

### ISSUE THREAD

**Issue by digitalisx** [horensic/evtxrensic#1]
## Log List - Time Column Resize Bug
Event Log를 불러오고 Filterig된 Log를 볼 수 있는 Log List에서의 Bug입니다.

다른 Table의 Column Size의 조절에는 문제가 없습니다만, 발생하는 Bug는 아래와 같습니다.
 
> **"_로그 시간_" 관련 Column의 크기가 변경되지 않습니다.**

"로그 시간" 관련 Column 또한 크기 변경이 가능하도록 수정이 필요 해보입니다.

![image](https://user-images.githubusercontent.com/16293464/33110040-7e0a54f0-cf88-11e7-91bc-7ab5ad7cf5d0.png)

**Comment by horensic** [comment]
버그 아닙니다.
